
# dataframe that holds usernames, passwords and other user data----
user_base <- tibble::tibble(
  user = c(
    "admin",
    "U-10g_trainer",
    "U-10w_trainer",
    "U-11g_trainer",
    "U-11w_trainer",
    "U-11z_trainer",
    "U-12g_trainer",
    "U-12w_trainer",
    "U-13g_trainer",
    "U-13w_trainer",
    "U-13z_trainer",
    "U-14_trainer",
    "U-15w_trainer",
    "U-15g_trainer", 
    "U-16_trainer",
    "U-17w_trainer",
    "U-17g_trainer",
    "Postformatie_trainer"),
  password = c("kvc_admin!",
               "kvc_u10g!",
               "kvc_u10w!",
               "kvc_u11g!",
               "kvc_u11w!",
               "kvc_u11z!",
               "kvc_u12g!",
               "kvc_u12w!",
               "kvc_u13g!",
               "kvc_u13w!",
               "kvc_u13z!",
               "kvc_u14!",
               "kvc_u15w!",
               "kvc_u15g!",
               "kvc_u16!",
               "kvc_u17w!",
               "kvc_u17g!",
               "kvc_pf!"),
  password_hash = sapply(c("kvc_admin!",
                           "kvc_u10g!",
                           "kvc_u10w!",
                           "kvc_u11g!",
                           "kvc_u11w!",
                           "kvc_u11z!",
                           "kvc_u12g!",
                           "kvc_u12w!",
                           "kvc_u13g!",
                           "kvc_u13w!",
                           "kvc_u13z!",
                           "kvc_u14!",
                           "kvc_u15w!",
                           "kvc_u15g!",
                           "kvc_u16!",
                           "kvc_u17w!",
                           "kvc_u17g!",
                           "kvc_pf!"), sodium::password_store),
  permissions =  c(
    "admin",
    "U-10g",
    "U-10w",
    "U-11g",
    "U-11w",
    "U-11z",
    "U-12g",
    "U-12w",
    "U-13g",
    "U-13w",
    "U-13z",
    "U-14",
    "U-15w",
    "U-15g",
    "U-16",
    "U-17w",
    "U-17g",
    "Postformatie")
)
#----
var_ploeg <- c("U-10g",
               "U-10w",
               "U-11g",
               "U-11w",
               "U-11z",
               "U-12g",
               "U-12w",
               "U-13g",
               "U-13w",
               "U-13z",
               "U-14",
               "U-15w",
               "U-15g",
               "U-16",
               "U-17w",
               "U-17g",
               "Postformatie")
current_year <- as.integer(format(Sys.Date(), "%Y"))
var_year <- 2021:current_year+1
var_season <- paste("season:", var_year - 1, "-", var_year)
var_month <- c(
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
)

SHEET_ID_HR_DB = readRDS("SHEET_ID_HR_DB")
SHEET_ID_HVP = readRDS("SHEET_ID_HVP")
SHEET_PERFORMANCE = readRDS("SHEET_PERFORMANCE")
SHEET_ID_PLAYER_INFO = readRDS("SHEET_ID_PLAYER_INFO")
SHEET_ID_MAX_HR = readRDS("SHEET_ID_MAX_HR")